version: 0.0
os: linux
files:
  - source: drupal
    destination: /var/www/drupal

hooks:
  ApplicationStop:
    - location: scripts/codedeploy-application-stop.sh
  AfterInstall:
    - location: scripts/codedeploy-after-install.sh