version: 0.0
os: linux
files:
  - source: drupal
    destination: /var/www/drupal

hooks:
  BeforeInstall:
    - location: scripts/codedeploy-before-install.sh
      runas: root
  AfterInstall:
    - location: scripts/codedeploy-after-install.sh
      runas: root
