# An authority as defined in RFC3986. An authority consists of host, optional userinfo and optional port. The host can
# be an IP address or registered domain name.
# @see https://tools.ietf.org/html/rfc3986#section-3.2
# @see \Drupal\cdn\Plugin\Validation\Constraint\CdnDomainConstraintValidator::isValidCdnDomain()
cdn.domain:
  type: string
  label: 'Domain'
  constraints:
    CdnDomain: []
# A scheme or a network-path reference as defined in RFC3986.
# @see https://tools.ietf.org/html/rfc3986#section-3.1
# @see https://tools.ietf.org/html/rfc3986#section-4.2
# @see \Drupal\cdn\Plugin\Validation\Constraint\CdnSchemeConstraintValidator::isValidCdnScheme()
cdn.scheme:
  type: string
  label: 'Scheme'
  constraints:
    CdnScheme: []
cdn.stream_wrapper_scheme:
  type: string
  label: 'Stream wrapper scheme'
  constraints:
    CdnStreamWrapper: []
