# This is a basic workflow to help you get started with Actions

name: AWS Patterns Ordinary Experts Patterns Drupal Example Site CI

on:
  push:
    branches: [ master, develop ]
    tags: [ '*' ]
  pull_request:
    branches: [ master, develop ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Compress Drupal code archive
      run: |
        tar cfz $HOME/aws-marketplace-oe-patterns-drupal-example-site.tar.gz \
        --exclude="sites/default/settings.local.php" \
        drupal
      working-directory: ${{ github.workspace }}

    - name: Install aws-cli
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Deploy archive to AWS S3 drop location
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.OE_PATTERNS_S3_DEV_GITHUB_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.OE_PATTERNS_S3_DEV_GITHUB_AWS_SECRET_ACCESS_KEY }}
      run: |
        export AWS_S3_DROP_PATH=${{ steps.extract_branch.outputs.branch }}/aws-marketplace-oe-patterns-drupal-example-site.tar.gz
        aws s3 cp $HOME/aws-marketplace-oe-patterns-drupal-example-site.tar.gz \
        s3://github-user-and-bucket-githubartifactbucket-1c9jk3sjkqv8p/$AWS_S3_DROP_PATH