# Workflow to compress drupal code and upload to AWS S3 drop location

name: AWS Patterns Ordinary Experts Patterns Drupal Example Site CI

on:
  push:
    branches: [ master, develop, 'feature/*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ master, develop, 'feature/*' ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Compress Drupal code archive
      run: |
        tar cfz $HOME/aws-marketplace-oe-patterns-drupal-example-site.tar.gz \
        --exclude="drupal/sites/default/settings.local.php" \
        --exclude=".git" \
        .
        zip -y -r $HOME/aws-marketplace-oe-patterns-drupal-example-site.zip . -x '*.git*'
      working-directory: ${{ github.workspace }}

    - name: Install aws-cli
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Deploy archive to AWS S3 drop location
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.OE_PATTERNS_S3_DEV_GITHUB_AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: us-east-1
        AWS_SECRET_ACCESS_KEY: ${{ secrets.OE_PATTERNS_S3_DEV_GITHUB_AWS_SECRET_ACCESS_KEY }}
      run: |
        export AWS_S3_DROP_PATH=aws-marketplace-oe-patterns-drupal-example-site/$GITHUB_REF.tar.gz
        aws s3 --debug cp $HOME/aws-marketplace-oe-patterns-drupal-example-site.tar.gz \
        s3://github-user-and-bucket-githubartifactbucket-wl52dae3lyub/$AWS_S3_DROP_PATH

        export AWS_S3_DROP_PATH_ZIP=aws-marketplace-oe-patterns-drupal-example-site/$GITHUB_REF.zip
        aws s3 --debug cp $HOME/aws-marketplace-oe-patterns-drupal-example-site.zip \
        s3://github-user-and-bucket-githubartifactbucket-wl52dae3lyub/$AWS_S3_DROP_PATH_ZIP
